### ISSUE TITLE
No mouse support 

### ISSUE THREAD

**Issue by wizard0072** [finalburnneo/FBNeo#1118]
Can not get dial or trackball working in both quester games or monkey magic all three games only seem to work with stick running on pi3.

**Comment by barbudreadmon** [comment]
It seems analog controls were never implemented in those drivers

**Comment by dinkc64** [comment]
Quester has been fixed, thanks for letting us know, hopefully will get to the other one soon! :)
best regards,
- dink

**Comment by dinkc64** [comment]
Monkey Magic is now hooked up as well, enjoy!

best regards,
- dink

**Comment by barbudreadmon** [comment]
note: i'll sync the libretro port soon, i just need to finish a few things first

**Comment by wizard0072** [comment]
I can confirm both Quester and Monkey magic work now on my pi3b build,only one still not working is questers special edition rom name (questers) but other then that many thanks peeps & take care

**Comment by dinkc64** [comment]
thanks for confirming, also thanks for letting know about questers - it's fixed now :)

**Comment by wizard0072** [comment]
Many thanks again.
p.s.
thought i quickly let you know incase your not aware 
of the following two games.
(msisaac)  Metal Soldier Isaac II - player 2 does not seem to work.Game stays on player 1
(ddayjlc & ddayjlca ) D-Day (Jaleco set 1) & D-Day (Jaleco set 2) - player 2 does not seem to work.Game stays on player 1

**Comment by dinkc64** [comment]
you're welcome!
msisaac - game has unemulated protection, and just a simple mcu simulation to get the game to work.  Until game's MCU is dumped, it will have some problems (p2 don't work)
unfortunately, exactly the same problem with ddayjlc.  I'll mark in the game notes for now to avoid confusion.

best regards,
- dink
