### ISSUE TITLE
Sound disappearing in Sonic Wings 2/Aero Fighters 2

### ISSUE THREAD

**Issue by player987386** [finalburnneo/FBNeo#1340]
Hi! First of all, thank you very much for FBN. As a FB user since the beginning, it's great to see how far it comes.

There's an old bug on Sonic Wings 2 when the sound (music+fx) stops randomly or strucks on a note/sound. I've seen this bug on the last FBA and FBN, however, on old FBA versions (circa 2004/2006) there's no bug, so I conclude something got messed up on the way. 

I've seen the bug on FBN 1.0.0.02 right now, but it's present on these gameplays where probably FBA was used:

23:45
https://www.youtube.com/watch?v=3RF_vWJHy5E

34:05
https://www.youtube.com/watch?v=AOWuUJi5Kac

Can you please fix it? Thanks!

PS. it's my first time posting on Github, so please forgive anything I may be doing wrong.

**Comment by dinkc64** [comment]
Hi,
Thanks for letting us know about the problem.  Could you record a replay using "Game -> Replay -> Record Input"?
Make sure to use the latest fbneo (10.0.0.03 dated yesterday or newer), at the recording dialog, make sure "Record from Power-On" and "With NVRAM" is checked.  Stop the recording at about a minute after the sound disappears then upload it here.  Just zip and drag the file to your message text, and it'll attach it :)

The latest FBNeo exe's can be gotten here: 
https://github.com/finalburnneo/FBNeo/releases/tag/latest
(If there aren't any files listed, try back in a few minutes - the system is builds a new version often)

best regards,
- dink

**Comment by player987386** [comment]
Hi dinkc64, thanks for the reply!

I'll download the new FBN and try to record the game next weekend.

Cheers!

**Comment by player987386** [comment]
@dinkc64  I made the recording as instructed, the bug appears at the beginning of stage 8 (low right counter at aprox. 34300). Hope that helps!

[sonicwi2_bug.zip](https://github.com/finalburnneo/FBNeo/files/10771872/sonicwi2_bug.zip)

**Comment by dinkc64** [comment]
Thanks for the recording!
I fixed some timing issues, and now the problem seems to be gone.  I even ended up playing it from beginning to end just to be sure.
Keep in mind: There will be a part right after defeating the monkey boss where all sound stops, I think in level 10.  I was pretty worried when this happened, but kept playing... It turns out it's part of the game - a dramatic entry to the next and final boss, what a relief. :)

Would you be willing to grab the update w/the new fix here, and make another recording to verify that the game I just played without problems wasn't just a fluke?
https://github.com/finalburnneo/FBNeo/releases/tag/latest

best regards,
- dink

**Comment by barbudreadmon** [comment]
FWIW, i sort of remember it isn't the first time we encounter audio issues in this game, and that they were somehow tied to the selected bios.

**Comment by dinkc64** [comment]
barbudreadmon,
i got tired of that speedhack code, it should have been called badhack.  if the timing was even slightly off, it could have lost a latch from or to the soundcpu.  the way I have it now: it should never lose a latch, regardless of timing.  Can you try to find info on which bios had trouble with it so I can test?

**Comment by player987386** [comment]
@dinkc64 Yeah, the music stopping at the monkey part is by design. :)

Unfortunately, the bug is still there. Occurs a lot less, before it was some 3 times for 5 gameplays. But it just happened, after aprox. 10 gameplays. Something I've noticed: altough it happens at any stage, stage 8 is where I've seen it happens more, specifically just before the boss.

BIOS used:
MVS Asia/Europe ver. 6 (1 slot)

I made another recording. Stage 8, before the boss. Please, check it out. I can try using another BIOS versions, if it makes sense.

[sonicwi2_bug-2.zip](https://github.com/finalburnneo/FBNeo/files/10775425/sonicwi2_bug-2.zip)

**Comment by dinkc64** [comment]
Thanks for all your help!
I've made another modification, hopefully this will be the last time I will need you to test:)

best regards,
- dink

**Comment by barbudreadmon** [comment]
@dinkc64 i couldn't find that old issue, but i'm pretty sure it was something about some sounds not playing when using an usa bios, i'm wondering if it wasn't on sonic wings 3 though.

**Comment by player987386** [comment]
@dinkc64 No problem man, I like this game a lot so playing it is not an issue! :)

But.... bug still there. :( Now at stage 2, during the boss fight. It was the 4th gameplay in a row. Same settings, and using the x32 version. Recording attached.

Do you think the romset may be the culprit? It's an old rom, been using it for years in both Mame and FBA-2005. 

Now I thank you for the effort to fix the issue. I'm not a programmer but I can imagine the hard work trying to find these elusive bugs. :)

----

PS 1: Regarding Sonic Wings 3, there's a BIOS issue where the Europe version is so difficult to the point of being unplayable. Japan and USA BIOS are fine. 

PS 2: I tried to open the first recording I did on the new EXE version and it worked like a charm (and without any sound bug!) So, I conclude there is no problem using the recordings and savestates I made on FBN 3.0.0.02 on newer versions, right?

[sonicwi2_bug-3.zip](https://github.com/finalburnneo/FBNeo/files/10778088/sonicwi2_bug-3.zip)

**Comment by dinkc64** [comment]
@player987386
Hmmm, I'm going to have to think about this for a bit.  
In the meantime could you please zip/attach your config/fbneo.ini file and config/games/sonicwi2.* files?
Also can you verify that playing back the sonicwi2_bug-3 replay will cause the bug to happen?

p.s. states and replays from .02 are incompatible with .03.

best regards,
- dink

**Comment by dinkc64** [comment]
@barbudreadmon, thanks for checking!

**Comment by player987386** [comment]
@dinkc64  I always test the recording before sending it, to make sure it caught the bug. :)

Here's my config files. Feel free to ask any further testing/info you may need from me.

Cheers and have a good week!


[sonicwi2_config.zip](https://github.com/finalburnneo/FBNeo/files/10779390/sonicwi2_config.zip)

**Comment by dinkc64** [comment]
@player987386 thanks again! :)
I have another test for you, -hopefully- getting close this time! :)
available at the same usual place:
https://github.com/finalburnneo/FBNeo/releases/tag/latest

best regards,
- dink

**Comment by player987386** [comment]
@dinkc64  Good news! played a lot today (and I mean A LOT) and bingo! No sound bug at all!!! \o/

Tried various pilots, mixed stage orders, different strategies.  Everything working just fine. I think you nailed it! Thank you very much for your hard work!

I'll do some additional tests tomorrow and close the issue. :)

Cheers!!


PS. what's the best way for updating FBN? Just delete the EXE or is it good practice to delete everything and start fresh?

**Comment by dinkc64** [comment]
woo-hoo! :D 
wow, what great day!  Thanks for all your help with this!

For upgrading - personally I just copy the new exe over the old one, clear out the savestates directory so that old states don't accidentally get loaded though.  Loading old states in new fbn can be bad (crash the game, or worse).  (hopefully I can do something about this, some day)

best regards,
- dink

**Comment by dinkc64** [comment]
A technical write-up on this issue, hopefully someone will find this useful some day :)

Sonic Wings 2 - music dies bug

For this bug to happen, a very special chain of events have to happen
at the same time.

set-up
1: 16e1: z80 sent the first part of a ym2610 address to address port
2: the second part of the ym2610-data is supposed to go out at 16f4, before
interrupts are enabled
3: ei enables interrupts, but, has 1-opcode latency, meaning interrupts will
be "enabled" after 16f4 has executed!
4: because a nmi hits directly after ei, it mops up thet 1-opcode latency, so
when it returns, an irq could possibly hit before "out (c), a"

-code from problem area-
16e0: di          // disable irq
16e1: out (c), a  // output ym2610 address to address port
...
16f3: ei          <- nmi hits here (sound-command from 68k)
                  <- upon return from nmi, irq from ym2610 timer hits here
16f4: out (c), a  // output ym2610 data to data port

it happens:
1: after ei executes, a soundcommand comes in from the 68k and a nmi hits before
16f4 executes
2: right as the nmi returns (retn), an irq comes in from the ym2610 timer,
so, we take the irq, and come back, and execute 16f4 out (c),a

remember: irq is never supposed to hit before "out (c), a" completes

during the ym2610 timer irq, the z80 sends out some commands to the ym2610 to
continue to play the background music & restart timers & etc. -but we're halfway
into a command to the ym2610 already!-
n.b.: a command to ym2610 is a 2 part process:
1. write to the address port
2. write to the data port

at this point, the ym2610 timer stops, irq's are no longer generated and
music/sounds go quiet.

The first fix I came up with is probably wrong (or right?) - delay nmi until
the "after ei latency" logic, but nmi's aren't supposed to ever be delayed.
some z80 cores (found randomly on github, etc) actually do this, though.

The second one makes a bit more sense, I found some research by floooh regarding
retn-iff1-latency.  retn is "return from nmi handler", which delays enabling
irq until after the fetch of the next opcode.  meaning - 16f4 will complete
before the irq hits, as it should.

**Comment by player987386** [comment]
Hi!

Tried the game a couple times  today and everything is working as expected. Also, I saw on the forum you asking  users to try other Neo Geo games, so I did some testing with Fatal Fury Special and Sonic Wings 3. Didn't notice anything wrong in both games. :)

 @dinkc64 again, thank you very much for your hard work!!

**Comment by dinkc64** [comment]
Hi @player987386,
Awesome!  I'm really glad this worked out - thanks so much for your help! :)

best regards,
- dink
