### ISSUE TITLE
libretro - Can't use Service button in game Pu·Li·Ru·La (Arcade/Taito)

### ISSUE THREAD

**Issue by djlain** [finalburnneo/FBNeo#1850]
The game roms are pulirula/pulirulaj/pulirulaa.

In the game you need Service button to enter the Stage Select Mode (Resource: https://tcrf.net/PuLiRuLa_(Arcade)#Stage_Select), it's reachable by using standalone FinalBurn Neo because there is a individual key for it (default setting is 9 on keyboard), video sample:

https://github.com/user-attachments/assets/fbdbad79-3643-4654-ac2f-fdedbbadec3b

But in libretro core with retroarch, there is no individual key for Service button, also no Diagnostic Menu in core menu like NeoGeo games. It's possible to change some game settings in DIP switches menu and go to Service Mode though, but still impossible to enter Stage Select Mode due to no Service button, like in this video (The libretro core and retroarch version are all latest, up to today):

https://github.com/user-attachments/assets/b1513b69-0674-421a-a374-27a33721c4f6

Hoping it's possible to config individual key for Service button in future updates. Thanks very much!

**Comment by barbudreadmon** [comment]
Thanks for the report, i'll map that button soon.

**Comment by barbudreadmon** [comment]
Done :)

**Comment by djlain** [comment]
Thanks very much for the quick replying!! I tried update the core to the latest version (which was v1.0.0.03 6fbc30a) and also update retroarch to the latest nightly vesion today, but it seems still not able to map service button in quick menu -> controls. Am I doing wrong or need to wait for a newer update? Thanks!!

**Comment by barbudreadmon** [comment]
I can only suppose the libretro buildbot hasn't finished updating the core yet.

**Comment by djlain** [comment]
I see, will stay tuned for that, much appreciate!

**Comment by djlain** [comment]
Just update the core to the latest version and the issue solved! Thanks again for the hard work!
