### ISSUE TITLE
Graphic issues in some Mega Drive games

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1919]
Hi,
since the November 16th modification ( https://github.com/finalburnneo/FBNeo/commit/5172a59b066b605f4d2f6b3c6178819abec8e80e ) some graphical issues appeared in other Mega Drive games. These are some examples :

![bugs](https://github.com/user-attachments/assets/c47877da-d0e9-4121-ad35-5e5db8d598b9)

* Streets of Rage misses a graphic line above the score.
* F1 (Euro) has some graphic issues in the left part of the screen.

The pictures from the left are from the November 15th version and the ones from the right are the pictures from the November 16th modification (and later versions). There might be more games affected but these are the two games that we know for sure for now (testing some games randomly). Can you fix the problem so all the affected games work perfectly again, please?
 
Thank you!

**Comment by dinkc64** [comment]
Hi dangonzilla, 
Thanks for letting me know, do you know any other games that have issues?

best regards,
- dink

**Comment by dinkc64** [comment]
Please test again with the new exe's :)

**Comment by dangonzilla** [comment]
Thank you very much! We've tested those games and the problems are solved. If we find more games with graphical problems we would tell you. 

There is another thing that it has nothing to do with the problem reported in this thread. There are many Mega Drive games that opens and closes the emulator many times in their intros (loading the Sega logo and the game intros; there isn't that issue while playing them), like Street of Rage 3. Can you take a look at it?

**Comment by dinkc64** [comment]
Hi dangonzilla,
That's good news, thanks for testing!

SOR3 changes the video mode several times, and if its set to "Resize Screen/window" for "32col mode draw" in the dips, it will be irritating like you mentioned.  Though, the video quality is better this way.  Change the option to "Inner Zoom" and it will stop changing the mode, with slightly less quality of video for 32col mode. 

best regards,
- dink

**Comment by khanhnguyen1988** [comment]
hi . Some Street of Rage 2 hacks also have problem with emulator closes and opens when switching scenes
https://www.youtube.com/watch?v=Szj2T-MFWO8

fbneo video
md_sor2tmntsr  Teenage Mutant Ninja Turtles: Shredder's Re-Revenge (GlobalHack, v1.01)
https://www.youtube.com/watch?v=N2DEciK2NpY

**Comment by dinkc64** [comment]
@khanhnguyen1988 
Dips -> ""32col mode draw", change to "Inner Zoom" 

best regards,
- dink

**Comment by khanhnguyen1988** [comment]
> @khanhnguyen1988 Dips -> ""32col mode draw", change to "Inner Zoom"
> 
> best regards,
> 
> * dink
Yes. It still happens when changing the switches "Inner Zoom" . Emulator closes and opens

https://github.com/user-attachments/assets/b9cbf2b8-5f96-455e-ad03-bbeb341a71e9

![Screenshot 2024-11-22 140102](https://github.com/user-attachments/assets/482e8ad8-cbfe-4725-9403-aa1dd2d9cba1)

**Comment by dinkc64** [comment]
@khanhnguyen1988 
Sorry, I made a bug - but it's fixed now.  Please update fbn exe and try again :)

**Comment by khanhnguyen1988** [comment]
@dinkc64  Thank you very much! I tested those games and the problems are solved.

**Comment by dangonzilla** [comment]
Hi @dinkc64 ,

We've tested FBNeo with that option and it works perfectly.

Thank you very much!

**Comment by dinkc64** [comment]
@dangonzilla & @khanhnguyen1988,
Thanks again for all your good bug reports and testing, it's really a big help for this project :)

best regards,
- dink
