### ISSUE TITLE
T & W Unit video issues

### ISSUE THREAD

**Issue by tmaul** [finalburnneo/FBNeo#39]
Not sure if it's related to the duping/skipping mentioned in an issue @https://github.com/libretro/FBNeo/issues/12 but in Visual Studio 2019  the screen doesn't update at all. Looking into it more: I've discovered it never hits certain memory handlers e.g. the IO one declared in the TMS init or any of the DMA ones in MK1.  @dinkc64 last build posted at neosource works ok though so maybe GCC is better at hiding whatever the problem is. If I can ever get enough time to read the CMake instructions, I would like to try a clang build but other than that I've hit my skill limit on this one!

**Comment by dinkc64** [comment]
It shouldn't be related, but that is weird - the games worked fine in b***y's vs builds.  I have no idea what could be wrong :(

**Comment by barbudreadmon** [comment]
It might be related : i remember those games having the same issue here with gcc when using `-O0`

**Comment by dinkc64** [comment]
hmm, well, I'd be interested to know if they still do that w/-O0.  let me know, and tomorrow I'll investigate.
best regards,
- dink

**Comment by barbudreadmon** [comment]
It still does that with -O0 on my 64bits linux libretro core, i hear a sound in the background (some kind of beep) which is not a sound the game produces when built with -O1/-O2/-O3 (where the issue with half of the frames being skipped is happening).
Built with gcc-8.2 btw, and no issue is showing in asan/ubsan.
Also tried removing all c(xx)flags, or using -O0 + all the cflags supposedly making the difference between -O0 and -O1, but i got the same result.

**Comment by tmaul** [comment]
That beeping noise is exactly what happens here with visual studio

**Comment by barbudreadmon** [comment]
@tmaul that's good to know, it seems like it's the same issue then

@dinkc64 i'm not sure you can reproduce this issue on windows's gcc, i kinda remember we talked about this a few months ago and you couldn't reproduce it on your side with -O0

**Comment by tmaul** [comment]
fixed in e87e71f

**Comment by tmaul** [comment]
@barbudreadmon  Could you check if this fixes the issue in your 64bit linux build please? I probably should have done that before closing the issue but the heat has gotten to me :)

**Comment by barbudreadmon** [comment]
Yes, i don't see frame duping anymore, congratulations on fixing this !

**Comment by dinkc64** [comment]
are you sure?
When the game first starts up, it is in a non-dma mode.  It is not until the character select or play screen  that it goes into this dma mode and the cpu does not provide the correct data for every other scene/frame.    at least, this is how I notice in mk.
barbudreadmon, where do you see it fixed at?

**Comment by barbudreadmon** [comment]
I tested on mk by setting frameskip so it would skip half of the frames, usually it would result in the game not refreshing correctly, because the game itself would also frameskip half of the frames but in a more random way, so regularly my frameskip setting would only try to draw the "non-existent" frame for a period of several seconds.
There might still be issues (?) but at the very least i can tell it seems a lot better on my side.

**Comment by dinkc64** [comment]
oh, well that's good then.
how notice the skipped frames:
start game of mk
when game starts, pause and single step, notice only every other frame gets updated.
If this is not the case - something amazing has happened and we are on the verge of a real fix.  please let me know! :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
You are right, while it's a lot better, the issue isn't completely solved, i think the game is still showing only ~27 different frames per second, and sometimes i'm still getting the issue i mentioned when setting frameskip (a lot more scarcely though).

**Comment by dinkc64** [comment]
It all depends on if the frame it's actually drawing is getting skipped or not :)  ohwell..

**Comment by tmaul** [comment]
I'll take a look at this in the debugger again this weekend to see if it does any other jumps to code it shouldn't now the games are running in VS2019.
